openapi: "3.0.0"
info:
  title: "Product List and Shopping Cart API"
  version: "1.0.0"
  description: >
    The Product List and Shopping Cart API is a comprehensive RESTful service
    designed to power eCommerce platforms. Built with Express.js and MongoDB,
    this API provides secure and efficient management of user accounts, product
    catalogs, and shopping cart operations.
  contact:
    name: "Richard Essuman"
    email: "ressuman001@gmail.com"
    url: "https://github.com/ressuman/Backend-Assessment-Product-List-Cart-Directory-Project.git"
termsOfService: "http://swagger.io/terms/"
license:
  name: "Apache 2.0"
  url: "http://www.apache.org/licenses/LICENSE-2.0.html"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
servers:
  - url: "http://localhost:5030"
    description: "Local development server (HTTP)"
  - url: "https://api.yourdomain.com"
    description: "Production server (HTTPS)"
components:
  securitySchemes:
    bearerAuth:
      type: "http"
      scheme: "bearer"
      bearerFormat: "JWT"
security:
  - bearerAuth: []
